GET http://localhost:5500/api/v1/subscriptions/user/694249f1145aa50fe0284ad0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQyNDlmMTE0NWFhNTBmZTAyODRhZDAiLCJpYXQiOjE3NjU5NTE5ODUsImV4cCI6MTc2NjAzODM4NX0.RUno1NDOUnHRvvuoW4TQps2Yy-YLs0GBVFwAiJCCRAw
